### ISSUE TITLE
Copy and Deploy MUI Documentation Format

### ISSUE THREAD

**Issue by codeadamca** [BrickMMO/docs-v2#1]
Copy the documentation React website from MUI and see if we can use it to structure the documentation for BrickMMO. For this task copy the documentation React/MUI website and see if you can get it working locally.

The docs portion of MUI is available here:

https://github.com/mui/material-ui/tree/master/docs

Make sure to change the build directory to `docs`.

**Comment by bingjetli** [comment]
# Overview
Hey, it's been a while since I updated this project. I had some time over the reading week to properly familiarize myself with the MUI repository as well as the tools they used to set up the mono-repo. 

After repeated tinkering, I managed to get a reasonably clean extraction of their documentation website from the mono-repo. The dev server, building process and export process all work as far as I can tell. I've also changed their export path to `docs` and pushed all my changes to a new branch called `issue-1`. 

I also have a separate markdown file of notes I took during the entire process that I haven't uploaded as of yet. I've included the changelog section of the notes in case you wanted to see what I did to get this working.

# Changelog
Copied `.gitignore` and `.gitattributes` over from the monorepo to the project directory.

Added `workspaces` field to the `package.json`. Added `packages/*` as an entry to the workspaces. Yarn workspaces seem to allow local/internal packages to automatically be linked during installation. This also lets us make changes to their internal packages without relying on their pre-built public packages.

Changed referenced `docs` package path to `../../` in `packages/api-docs-builder/package.json`. Cyclic dependency.

Moved `tslint.json` from the monorepo to `base-tslint.json` in the project directory.

Changed reference to a `tslint.json` in the monorepo to `base-tslint.json`.

Moved `tsconfig.json` from the monorepo to `base-tsconfig.json` in the project directory.

Changed reference to a `tsconfig.json` in the monorepo to `base-tsconfig.json`.

Changed `workspaceRoot` reference from monorepo to current project directory in `next.config.js`. See `§1698889907`

Changed `pkg` reference from monorepo's `package.json` to current project's `package.json`. See `§1698889825`

Changed reference to `docs/export` in `base-tsconfig.json` to `docs`.

Changed `export` script in `package.json` from 
`"export": "rimraf docs/export && next export --threads=3 -o export && yarn build-sw",` to 
`"export": "rimraf docs && next export --threads=3 -o docs && yarn build-sw",`

Changed `swDest` in `./scripts/buildServiceWorker.js` to reflect new export destination. See `§1698788654`

Changed all references from `../packages` to `./packages` in `babel.config.js` and `next.config.js`.

Changed reference to `docs/public/*` to `public/*` in `packages/markdown/prepareMarkdown.js`.

Changed reference to `pages/production-error/ErrorDecoder.js` in `src/pages/production-error/index.md` to `./ErrorDecoder.js`. See `¶1698901645`.

Changed reference to `pages/versions/ReleasedVersions.js` in `src/pages/versions/versions.md` to `./ReleasedVersions.js`. See `¶1698901645`.

Changed reference to `pages/versions/LatestVersions.js` in `src/pages/versions/versions.md` to `./LatestVersions.js`. See `¶1698901645`.

**Comment by codeadamca** [comment]
Thanks for an awesome update!

We should put the markdown notes you have into the repo README.MD file! And next time we're working on projects you can give me a quickk tour of your code! I'd also like to confirm that the end result is client-side only. If so, we can deploy using GitHub Pages.

**Comment by bingjetli** [comment]
Just updating this issue for the document conversion assignment! The documentation site is up and running. The dev server, build and static export deployment all work as expected too.
